import os
import google_auth_oauthlib.flow
import googleapiclient.discovery
import googleapiclient.errors
from googleapiclient.http import MediaFileUpload
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
import argparse

# Define the scopes required for uploading
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def authenticate_youtube():
    """
    Authenticates the user and returns the YouTube API service object.
    Supports headless execution (like Kaggle) by reusing 'token.json'.
    If 'token.json' doesn't exist, it will require local execution first to generate it.
    """
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

    api_service_name = "youtube"
    api_version = "v3"
    client_secrets_file = "client_secrets.json"
    token_file = "token.json"

    credentials = None

    # Check if we already have a saved token
    if os.path.exists(token_file):
        credentials = Credentials.from_authorized_user_file(token_file, SCOPES)

    # If there are no (valid) credentials available, let the user log in.
    if not credentials or not credentials.valid:
        if credentials and credentials.expired and credentials.refresh_token:
            credentials.refresh(Request())
        else:
            if not os.path.exists(client_secrets_file):
                raise FileNotFoundError(f"Missing {client_secrets_file}. Please download it from Google Cloud Console.")

            # Note: This step REQUIRES a local machine with a browser!
            print("No valid token.json found. Opening browser for authentication...")
            print("NOTE: If you are running this in Kaggle, this will fail. You must run this locally first to generate token.json, then upload token.json to Kaggle.")
            flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(
                client_secrets_file, SCOPES)
            credentials = flow.run_local_server(port=0)

        # Save the credentials for the next run
        with open(token_file, 'w') as token:
            token.write(credentials.to_json())

    youtube = googleapiclient.discovery.build(
        api_service_name, api_version, credentials=credentials)

    return youtube

def upload_video(youtube, file_path, title, description, tags, category_id="22", privacy_status="private"):
    """
    Uploads a video to YouTube.
    For Shorts, ensure the video is vertical (e.g. 9:16 aspect ratio), less than 60s,
    and includes #Shorts in the title or description.
    """
    print(f"Uploading {file_path} to YouTube...")

    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": category_id
        },
        "status": {
            "privacyStatus": privacy_status, # "private", "unlisted", or "public"
            "selfDeclaredMadeForKids": False
        }
    }

    # Call the API's videos.insert method to create and upload the video.
    insert_request = youtube.videos().insert(
        part=",".join(body.keys()),
        body=body,
        media_body=MediaFileUpload(file_path, chunksize=-1, resumable=True)
    )

    response = insert_request.execute()
    print(f"Upload Successful! Video ID: {response['id']}")
    print(f"URL: https://www.youtube.com/watch?v={response['id']}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Upload a video to YouTube Shorts")
    parser.add_argument("--file", type=str, required=True, help="Path to the video file to upload")
    parser.add_argument("--title", type=str, required=True, help="Video title (include #Shorts for Shorts)")
    parser.add_argument("--description", type=str, default="Generated by LTX-Video AI #Shorts", help="Video description")
    parser.add_argument("--tags", type=str, default="ai,ltx-video,shorts", help="Comma-separated tags")
    parser.add_argument("--privacy", type=str, default="private", choices=["public", "private", "unlisted"], help="Privacy status")

    args = parser.parse_args()

    if not os.path.exists(args.file):
        print(f"Error: Video file not found at {args.file}")
        exit(1)

    try:
        youtube_service = authenticate_youtube()
        tags_list = [tag.strip() for tag in args.tags.split(",")]
        upload_video(
            youtube_service,
            file_path=args.file,
            title=args.title,
            description=args.description,
            tags=tags_list,
            privacy_status=args.privacy
        )
    except Exception as e:
        print(f"An error occurred: {e}")
